# Generated by Django 5.1.4 on 2024-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pseudo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
