# Generated by Django 5.1.4 on 2024-12-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_pseudo_alter_profile_unique_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousmessage',
            name='ip_address',
        ),
    ]
