# Generated by Django 5.1.4 on 2024-12-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_anonymousmessage_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousmessage',
            name='readden',
            field=models.BooleanField(default=True),
        ),
    ]
